#######################################
# Function: 2_Create_soil_data-Millennial_LRF.R
# Author: Ellen Maas
# Date: July 11, 2022
# Description: Writes the Millennial-formatted data generated by
# the 2_Create_soil_data-setup scripts to the relevant folder
# for the LRF site.
#######################################

print(paste0("2_Create_soil_data-Millennial_",site_name,".R"))

###########################
# Millennial
###########################


##Soil parameter set

###########################
# create parameter files

# param_pc = slope of mineral C - clay relationship from Georgiou et al.
# soil_df[4,] is 10-20 cm depth
parameters <- data.frame(param_name = c("param_pH","param_bulkd","param_pc","param_claysilt"),
                         param_value = c(soil_df[4,"phaq_value_avg"],soil_df[4,"bdfiod_value_avg"]*1000,0.86,
                                         (soil_df[4,"clay_fraction"]+soil_df[4,"sand_fraction"])*100
                                         )
                         )
  
###########################
# write parameter files
write.table(parameters, file=paste0(mill_path,"siteparams_in.txt"),
            row.names=F, quote=F, col.names=F, sep=' ')
