#######################################
# Function: 2_Create_soil_data-Millennial_KBS.R
# Author: Ellen Maas
# Date: July 11, 2022
# Description: Writes the Millennial-formatted data generated by
# the 2_Create_soil_data-setup scripts to the relevant folder
# for the KBS site. At KBS, there is only one siteparams_in.txt
# file (with this data). To account for the differing SOC 
# content at the experiment start, the soil parameters in 
# soilparams_in_#.txt were separately adjusted during 
# calibration.
#######################################

print(paste0("2_Create_soil_data-Millennial_",site_name,".R"))

###########################
# Millennial
###########################


###########################
# create parameter files

# param_pc = slope of mineral C - clay relationship from Georgiou et al.
# soil_df[4,] is the 10-20 cm depth
parameters <- data.frame(param_name = c("param_pH","param_bulkd","param_pc","param_claysilt"),
                         param_value = c(soil_df[4,"PH"],soil_df[4,"BD"]*1000,0.86,
                                         (soil_df[4,"ParticleSizeClay"]+soil_df[4,"ParticleSizeSilt"])))
  
###########################
# write parameter files
## this does NOT need scenario designators; always the same for the site
write.table(parameters, file=paste0(mill_path,"siteparams_in.txt"),
            row.names=F, quote=F, col.names=F, sep=' ')
