#######################################
# Function: 2_Create_soil_data-Daycent_base1.R
# Author: Ellen Maas
# Date: July 11, 2022
# Description: Writes the Daycent-formatted data generated by
# the 2_Create_soil_data-setup scripts to the relevant folder
# for the relevant site. At KBS, there are separate soils_#.in
# files for the 3 field treatments in order to calibrate the
# starting SOC in each, which were set differently in the 
# T1 vs. T2 and T3. This script just creates a generic soils.in
# file which serves as the basis for the scenario-specific
# versions which were manually created from this. At LRF,
# there wasn't enough difference in SOC between treatments
# so there are no manual versions; Daycent just uses what
# this script generates.
#######################################

print("2_Create_soil_data-Daycent_base1.R")

###########################
#Daycent
###########################

## cannot name with scenario numbers
write.table(soil_df[,c("upper_depth_cm","lower_depth_cm","BD","DUL","LL15","evap_coef",
                       "root_fraction","sand_fraction","clay_fraction","OM_fraction",
                       "deltamin","ksat_cmsec","PH")], 
#            file=paste0(daycent_path,"soils_",scenario_name,".in"),
            file=paste0(daycent_path,"soils_base1.in"),
            row.names=F, quote=F, col.names=F, sep=' ')

