---
title: "Weather_analysis"
author: "Ellen Maas"
date: "2024-06-02"
output: html_document
description: "Simple models to look for short-term trends (past 10 years) vs. 30-year."
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)
library(magrittr)
library(lubridate)
library(dplyr)

```

```{r constants}
#
kbs_experiment_start_year <- 2003
kbs_experiment_end_year <- 2021
kbs_experiment_start_date <- "2003-01-01"
kbs_experiment_end_date <- "2021-12-31"
kbs_fut_weather_path <- paste0("Data/CMIP6/KBS/")
kbs_daycent_path <- paste0("Daycent/KBS/")
end_fut_period_year <- 2050
end_fut_period_date <- "2049-12-31"
end_exp_period_year <- 2021

# 12-color palette with grey and black. Colors in order are:
#[1]black, [2]dark blue, [3]mint green, [4]light blue, [5]grey,
#[6]pink, [7]red, [8]orange, [9]yellow, [10]mauve, [11]royal blue,
#[12]forest green
cbPalette12 <- c("#000000","#0072B2","#009E73","#56B4E9","#999999",
                "#CC79A7","#D55E00","#E69F00","#F0E442","#882255",
                "#332288","#0B6329"
                )
                         

```

```{r KBS import, include=FALSE}

# Historical

## Use Daycent weather for historical, over the experimental period
#hist <- read.table(paste0("C:/Users/edmaas/Documents/Modeling/Daycent/",site_name,"/basic_exp.wth")) 
kbs_hist_exp <- read.table(paste0("C:/Users/alask/Documents/CaseStudy/Daycent/KBS/basic_exp.wth"))
colnames(kbs_hist_exp) <- c("day","month","year","dayofyear","h_tmax","h_tmin","h_rain_cm")
kbs_hist_exp$date=make_date(kbs_hist_exp$year, kbs_hist_exp$month, kbs_hist_exp$day)

# Future

## Use Daycent weather for historical, over the experimental period
kbs_baseln <- read.table(paste0("C:/Users/alask/Documents/CaseStudy/Daycent/KBS/basic_1.wth"))
colnames(kbs_baseln) <- c("day","month","year","dayofyear","bl_tmax","bl_tmin","bl_rain_cm")
kbs_baseln <- kbs_baseln[kbs_baseln$year<=end_fut_period_year,]
kbs_baseln$date=make_date(kbs_baseln$year, kbs_baseln$month, kbs_baseln$day)


```


```{r stats}

########## KBS ##########

  # precip change 
kbs_prec_ann_means <- kbs_hist_exp[,c("year","h_rain_cm")] %>%
  group_by(year) %>%
  summarize(prec_mean_cm=mean(h_rain_cm,rm.na=T))
##
kbs_prec_28_df <- kbs_prec_ann_means[kbs_prec_ann_means$year %in% c(1994:2021),c("year","prec_mean_cm")]
kbs_prec_28_fit <- lm(prec_mean_cm ~ year, data = kbs_prec_28_df)
kbs_prec_28_coef <- coef(kbs_prec_28_fit)
kbs_prec_28_first <- as.numeric(lapply(kbs_prec_28_fit["fitted.values"],dplyr::first))
kbs_prec_28_last <- as.numeric(lapply(kbs_prec_28_fit["fitted.values"],dplyr::last))
kbs_prec_28_change <- round(kbs_prec_28_last - kbs_prec_28_first,3)
##
kbs_prec_10_df <- kbs_prec_ann_means[kbs_prec_ann_means$year %in% c(2012:2021),c("year","prec_mean_cm")]
kbs_prec_10_fit <- lm(prec_mean_cm ~ year, data = kbs_prec_10_df)
kbs_prec_10_coef <- coef(kbs_prec_10_fit)
kbs_prec_10_first <- as.numeric(lapply(kbs_prec_10_fit["fitted.values"],dplyr::first))
kbs_prec_10_last <- as.numeric(lapply(kbs_prec_10_fit["fitted.values"],dplyr::last))
kbs_prec_10_change <- round(kbs_prec_10_last - kbs_prec_10_first,3)
##
kbs_prec_5_df <- kbs_prec_ann_means[kbs_prec_ann_means$year %in% c(2017:2021),c("year","prec_mean_cm")]
kbs_prec_5_fit <- lm(prec_mean_cm ~ year, data = kbs_prec_5_df)
kbs_prec_5_coef <- coef(kbs_prec_5_fit)
kbs_prec_5_first <- as.numeric(lapply(kbs_prec_5_fit["fitted.values"],dplyr::first))
kbs_prec_5_last <- as.numeric(lapply(kbs_prec_5_fit["fitted.values"],dplyr::last))
kbs_prec_5_change <- round(kbs_prec_5_last - kbs_prec_5_first,3)
##

```

```{r graph}


  
g_prec <- kbs_prec_ann_means %>%
  ggplot(aes(x=year,y=prec_mean_cm)) +
  geom_point() +
  geom_abline(intercept=kbs_prec_28_coef[1], slope=kbs_prec_28_coef[2], color="black") +
  geom_abline(intercept=kbs_prec_10_coef[1], slope=kbs_prec_10_coef[2], color="red") +
  geom_abline(intercept=kbs_prec_5_coef[1], slope=kbs_prec_5_coef[2], color="blue") 
  

g_prec

```

```{r}

# tmin change
kbs_tmin_ann_means <- kbs_hist_exp[,c("year","h_tmin")] %>%
  group_by(year) %>%
  summarize(tmin_mean_C=mean(h_tmin,rm.na=T))
##
kbs_tmin_28_df <- kbs_tmin_ann_means[kbs_tmin_ann_means$year %in% c(1994:2021),c("year","tmin_mean_C")]
kbs_tmin_28_fit <- lm(tmin_mean_C ~ year, data = kbs_tmin_28_df)
kbs_tmin_28_coef <- coef(kbs_tmin_28_fit)
kbs_tmin_28_first <- as.numeric(lapply(kbs_tmin_28_fit["fitted.values"],dplyr::first))
kbs_tmin_28_last <- as.numeric(lapply(kbs_tmin_28_fit["fitted.values"],dplyr::last))
kbs_tmin_28_change <- round(kbs_tmin_28_last - kbs_tmin_28_first,3)
##
kbs_tmin_10_df <- kbs_tmin_ann_means[kbs_tmin_ann_means$year %in% c(2012:2021),c("year","tmin_mean_C")]
kbs_tmin_10_fit <- lm(tmin_mean_C ~ year, data = kbs_tmin_10_df)
kbs_tmin_10_coef <- coef(kbs_tmin_10_fit)
kbs_tmin_10_first <- as.numeric(lapply(kbs_tmin_10_fit["fitted.values"],dplyr::first))
kbs_tmin_10_last <- as.numeric(lapply(kbs_tmin_10_fit["fitted.values"],dplyr::last))
kbs_tmin_10_change <- round(kbs_tmin_10_last - kbs_tmin_10_first,3)
##
kbs_tmin_5_df <- kbs_tmin_ann_means[kbs_tmin_ann_means$year %in% c(2017:2021),c("year","tmin_mean_C")]
kbs_tmin_5_fit <- lm(tmin_mean_C ~ year, data = kbs_tmin_5_df)
kbs_tmin_5_coef <- coef(kbs_tmin_5_fit)
kbs_tmin_5_first <- as.numeric(lapply(kbs_tmin_5_fit["fitted.values"],dplyr::first))
kbs_tmin_5_last <- as.numeric(lapply(kbs_tmin_5_fit["fitted.values"],dplyr::last))
kbs_tmin_5_change <- round(kbs_tmin_5_last - kbs_tmin_5_first,3)
##
```

```{r}

g_tmin <- kbs_tmin_ann_means %>%
  ggplot(aes(x=year,y=tmin_mean_C)) +
  geom_point() +
  geom_abline(intercept=kbs_tmin_28_coef[1], slope=kbs_tmin_28_coef[2], color="black") +
  geom_abline(intercept=kbs_tmin_10_coef[1], slope=kbs_tmin_10_coef[2], color="red") +
  geom_abline(intercept=kbs_tmin_5_coef[1], slope=kbs_tmin_5_coef[2], color="blue") 
  

g_tmin
  
```

```{r}

# tmax change
kbs_tmax_ann_means <- kbs_hist_exp[,c("year","h_tmax")] %>%
  group_by(year) %>%
  summarize(tmax_mean_C=mean(h_tmax,rm.na=T))
##
kbs_tmax_28_df <- kbs_tmax_ann_means[kbs_tmax_ann_means$year %in% c(1994:2021),c("year","tmax_mean_C")]
kbs_tmax_28_fit <- lm(tmax_mean_C ~ year, data = kbs_tmax_28_df)
kbs_tmax_28_coef <- coef(kbs_tmax_28_fit)
kbs_tmax_28_first <- as.numeric(lapply(kbs_tmax_28_fit["fitted.values"],dplyr::first))
kbs_tmax_28_last <- as.numeric(lapply(kbs_tmax_28_fit["fitted.values"],dplyr::last))
kbs_tmax_28_change <- round(kbs_tmax_28_last - kbs_tmax_28_first,3)
##
kbs_tmax_10_df <- kbs_tmax_ann_means[kbs_tmax_ann_means$year %in% c(2012:2021),c("year","tmax_mean_C")]
kbs_tmax_10_fit <- lm(tmax_mean_C ~ year, data = kbs_tmax_10_df)
kbs_tmax_10_coef <- coef(kbs_tmax_10_fit)
kbs_tmax_10_first <- as.numeric(lapply(kbs_tmax_10_fit["fitted.values"],dplyr::first))
kbs_tmax_10_last <- as.numeric(lapply(kbs_tmax_10_fit["fitted.values"],dplyr::last))
kbs_tmax_10_change <- round(kbs_tmax_10_last - kbs_tmax_10_first,3)
##
kbs_tmax_5_df <- kbs_tmax_ann_means[kbs_tmax_ann_means$year %in% c(2017:2021),c("year","tmax_mean_C")]
kbs_tmax_5_fit <- lm(tmax_mean_C ~ year, data = kbs_tmax_5_df)
kbs_tmax_5_coef <- coef(kbs_tmax_5_fit)
kbs_tmax_5_first <- as.numeric(lapply(kbs_tmax_5_fit["fitted.values"],dplyr::first))
kbs_tmax_5_last <- as.numeric(lapply(kbs_tmax_5_fit["fitted.values"],dplyr::last))
kbs_tmax_5_change <- round(kbs_tmax_5_last - kbs_tmax_5_first,3)

```


```{r}

g_tmax_28 <- kbs_tmax_28_df %>%
  ggplot(aes(x=year,y=tmax_mean_C)) +
  geom_point() +
    geom_smooth(method='lm', formula= y~x, se=FALSE, aes(colour = source)
                ,linewidth=0.75) +
  
  geom_abline(intercept=kbs_tmax_28_coef[1], slope=kbs_tmax_28_coef[2], color="black") +
  geom_point(data=kbs_tmax_10_df, aes(x=year,y=tmax_mean_C,color="red")) +
  geom_segment()
  
g_tmax_10 <- kbs_tmax_10_df %>%
  ggplot(aes(x=year,y=tmax_mean_C)) +
  geom_point() +
  geom_abline(intercept=kbs_tmax_10_coef[1], slope=kbs_tmax_10_coef[2], color="red") 

g_tmax_5 <- kbs_tmax_5_df %>%
  ggplot(aes(x=year,y=tmax_mean_C)) +
  geom_abline(intercept=kbs_tmax_5_coef[1], slope=kbs_tmax_5_coef[2], color="blue") 

g_tmax_28
  
```

```{r}

# # make dataframe with changes
# change_df <- data.frame(kbs_prec=c(kbs_prec_gfdl_low_change,kbs_prec_gfdl_high_change,
#                                    kbs_prec_ukesm_low_change,kbs_prec_ukesm_high_change),
#                         kbs_tmin=c(kbs_tmin_gfdl_low_change,kbs_tmin_gfdl_high_change,
#                                    kbs_tmin_ukesm_low_change,kbs_tmin_ukesm_high_change),
#                         kbs_tmax=c(kbs_tmax_gfdl_low_change,kbs_tmax_gfdl_high_change,
#                                    kbs_tmax_ukesm_low_change,kbs_tmax_ukesm_high_change),
#                         lrf_prec=c(lrf_prec_gfdl_low_change,lrf_prec_gfdl_high_change,
#                                    lrf_prec_ukesm_low_change,lrf_prec_ukesm_high_change),
#                         lrf_tmin=c(lrf_tmin_gfdl_low_change,lrf_tmin_gfdl_high_change,
#                                    lrf_tmin_ukesm_low_change,lrf_tmin_ukesm_high_change),
#                         lrf_tmax=c(lrf_tmax_gfdl_low_change,lrf_tmax_gfdl_high_change,
#                                    lrf_tmax_ukesm_low_change,lrf_tmax_ukesm_high_change))
# 
# # write out table
#     write.csv(change_df, file="../../Comb_results_2050/fut_clim_stats.csv",
#               row.names=c("GFDL Low","GFDL High","UKESM Low","UKESM High"))

```

<!-- ```{r tmin_group_data} -->

<!-- kbs_tmin_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_tmin")], -->
<!--                                          kbs_baseln[,c("date","bl_tmin")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    kbs_gfdl_low[,c("date","gl_tmin")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              kbs_gfdl_high[,c("date","gh_tmin")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        kbs_ukesm_low[,c("date","ul_tmin")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  kbs_ukesm_high[,c("date","uh_tmin")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="KBS", -->
<!--          clim_var="Min Temp") -->
<!-- colnames(kbs_tmin_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- kbs_tmin_piv <- pivot_longer(kbs_tmin_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- lrf_tmin_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_tmin")], -->
<!--                                          lrf_baseln[,c("date","bl_tmin")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    lrf_gfdl_low[,c("date","gl_tmin")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              lrf_gfdl_high[,c("date","gh_tmin")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        lrf_ukesm_low[,c("date","ul_tmin")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  lrf_ukesm_high[,c("date","uh_tmin")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="LRF", -->
<!--          clim_var="Min Temp") -->
<!-- colnames(lrf_tmin_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- lrf_tmin_piv <- pivot_longer(lrf_tmin_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- tmin_piv <- rbind(kbs_tmin_piv,lrf_tmin_piv) -->

<!-- ``` -->

<!-- ```{r tmax_group_data} -->

<!-- kbs_tmax_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_tmax")], -->
<!--                                          kbs_baseln[,c("date","bl_tmax")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    kbs_gfdl_low[,c("date","gl_tmax")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              kbs_gfdl_high[,c("date","gh_tmax")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        kbs_ukesm_low[,c("date","ul_tmax")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  kbs_ukesm_high[,c("date","uh_tmax")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="KBS", -->
<!--          clim_var="Max Temp") -->
<!-- colnames(kbs_tmax_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- kbs_tmax_piv <- pivot_longer(kbs_tmax_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- lrf_tmax_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_tmax")], -->
<!--                                          lrf_baseln[,c("date","bl_tmax")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    lrf_gfdl_low[,c("date","gl_tmax")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              lrf_gfdl_high[,c("date","gh_tmax")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        lrf_ukesm_low[,c("date","ul_tmax")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  lrf_ukesm_high[,c("date","uh_tmax")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="LRF", -->
<!--          clim_var="Max Temp") -->
<!-- colnames(lrf_tmax_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- lrf_tmax_piv <- pivot_longer(lrf_tmax_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- tmax_piv <- rbind(kbs_tmax_piv,lrf_tmax_piv) -->

<!-- ``` -->

<!-- ```{r rain_cm_group_data} -->

<!-- kbs_rain_cm_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_rain_cm")], -->
<!--                                          kbs_baseln[,c("date","bl_rain_cm")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    kbs_gfdl_low[,c("date","gl_rain_cm")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              kbs_gfdl_high[,c("date","gh_rain_cm")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        kbs_ukesm_low[,c("date","ul_rain_cm")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  kbs_ukesm_high[,c("date","uh_rain_cm")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="KBS", -->
<!--          clim_var="Rain") -->
<!-- colnames(kbs_rain_cm_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- kbs_rain_cm_piv <- pivot_longer(kbs_rain_cm_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- lrf_rain_cm_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_rain_cm")], -->
<!--                                          lrf_baseln[,c("date","bl_rain_cm")], -->
<!--                                          by="date", -->
<!--                                          all=TRUE), -->
<!--                                    lrf_gfdl_low[,c("date","gl_rain_cm")], -->
<!--                                    by="date", -->
<!--                                    all=TRUE), -->
<!--                              lrf_gfdl_high[,c("date","gh_rain_cm")], -->
<!--                              by="date", -->
<!--                              all=TRUE), -->
<!--                        lrf_ukesm_low[,c("date","ul_rain_cm")], -->
<!--                        by="date", -->
<!--                        all=TRUE), -->
<!--                  lrf_ukesm_high[,c("date","uh_rain_cm")], -->
<!--                  by="date", -->
<!--                  all=TRUE) %>% -->
<!--   mutate(site_name="LRF", -->
<!--          clim_var="Rain") -->
<!-- colnames(lrf_rain_cm_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High", -->
<!--                        "UKESM_Low","UKESM_High","SiteName","ClimateVariable") -->

<!-- lrf_rain_cm_piv <- pivot_longer(lrf_rain_cm_df, c(-Date,-SiteName,-ClimateVariable), -->
<!--                          names_to = "source", -->
<!--                          values_to = "val") -->

<!-- rain_cm_piv <- rbind(kbs_rain_cm_piv,lrf_rain_cm_piv) -->

<!-- ``` -->

<!-- ```{r combine} -->

<!-- alldata_piv <- rbind(tmin_piv,tmax_piv,rain_cm_piv) #%>% -->
<!--   #filter(Date<as.Date(end_fut_period_date)) -->


<!-- ``` -->







```{r limited_graph}

#### there is an issue associated with geom_smooth being used with the ylim 
#### command such that the data are displayed at the wrong vertical position, 
#### or sometimes even the wrong slope, depending on the range. this must be 
#### related to data points being excluded when ylim is set, so a truncated
#### set of data are being modeled. slopes are being calculated on the fly
#### this way, though, so that the facet_grid will work.

  g_temp_lim <- alldata_piv[alldata_piv$ClimateVariable %in% c("Max Temp","Min Temp") &
                          alldata_piv$source %in% c("Historical","Baseline","UKESM_High"),] %>%
    ggplot(aes(x=Date, y=val, color=source, show.legend=TRUE)) +
    # geom_point(show.legend=TRUE) +
    xlab("Year") +
    ylab(expression('Temperature ( ' ^o*'C)')) +
   # ylim(0,3) +
    ggtitle("Historical Temperature and Future Projections") +
    geom_smooth(method='lm', formula= y~x, se=FALSE, aes(colour = source)
                ,linewidth=0.75) +
    scale_color_manual(labels=c("Baseline","Historical","UKESM_High"),
                       values=cbPalette12[c(8,1,10)],
                       name="Climate Model") +
    facet_grid(ClimateVariable~SiteName) +
    theme_classic(base_family = "serif", base_size = 16) +
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "darkgrey", fill=NA),
          strip.background = element_blank(),
          axis.line = element_line(),
          legend.position = "right",
          legend.key = element_blank())
  
  g_temp_lim
  

    g_rain_lim <- alldata_piv[alldata_piv$ClimateVariable == "Rain" &
                          alldata_piv$source %in% c("Historical","Baseline","UKESM_High"),] %>%
    ggplot(aes(x=Date, y=val, color=source, show.legend=TRUE)) +
    #geom_point(show.legend=TRUE) +
    xlab("Year") +
    ylab(expression('Precipitation (cm)')) +
    #ylim(0,10) +
    ggtitle("Historical Precipitation and Future Projections") +
    geom_smooth(method='lm', formula= y~x, se=FALSE, aes(colour = source)
                ,linewidth=0.75,na.rm=TRUE) +
    scale_color_manual(labels=c("Baseline","Historical","UKESM_High"),
                       values=cbPalette12[c(8,1,10)],
                       name="Climate Model") +
    facet_wrap(~SiteName) +
    theme_classic(base_family = "serif", base_size = 16) +
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "darkgrey", fill=NA),
          strip.background = element_blank(),
          axis.line = element_line(),
          legend.position = "right",
          legend.key = element_blank())
  
  g_rain_lim

  #   g_rain2 <- ggplot(data=kbs_prec_gfdl_low_df) +
  #   # geom_point(show.legend=TRUE) +
  #   xlab("Year") +
  #   ylab(expression('Precipitation (cm)')) +
  #   ylim(0.25,0.35) +
  #   ggtitle("Historical Precipitation and Future Projections") +
  #   # geom_smooth(method='lm', formula= gl_rain_cm~date, se=FALSE, 
  #   #             aes(x=date, y=gl_rain_cm, colour = cbPalette12[4])
  #   #             ,linewidth=0.75,na.rm=TRUE, data=kbs_prec_gfdl_low_df) +
  #   # geom_smooth(method='lm', formula= gh_rain_cm~date, se=FALSE, 
  #   #             aes(x=date, y=gh_rain_cm, colour = cbPalette12[2])
  #   #             ,linewidth=0.75,na.rm=TRUE, data=kbs_prec_gfdl_high_df) +
  # 
  #   geom_abline(data=kbs_prec_gfdl_low_df,
  #               aes(intercept=kbs_prec_gfdl_low_coef[1], slope=kbs_prec_gfdl_low_coef[2], 
  #                   color=cbPalette12[4])) +
  #   geom_abline(data=kbs_prec_gfdl_high_df,
  #               aes(intercept=kbs_prec_gfdl_high_coef[1], slope=kbs_prec_gfdl_high_coef[2], 
  #                   color=cbPalette12[2])) +
  #   geom_abline(data=kbs_prec_ukesm_low_df,
  #               aes(intercept=kbs_prec_ukesm_low_coef[1], slope=kbs_prec_ukesm_low_coef[2], 
  #                   color=cbPalette12[6])) +
  #   geom_abline(data=kbs_prec_ukesm_high_df,
  #               aes(intercept=kbs_prec_ukesm_high_coef[1], slope=kbs_prec_ukesm_high_coef[2], 
  #                   color=cbPalette12[10])) +
  #   # geom_abline(intercept=kbs_prec_ukesm_low_coef[1], slope=kbs_prec_ukesm_low_coef[2], color=cbPalette12[6]) +
  #   # geom_abline(intercept=kbs_prec_ukesm_high_coef[1], slope=kbs_prec_ukesm_high_coef[2], color=cbPalette12[10]) +
  #   scale_color_manual(labels=c("GFDL_High","GFDL_Low",
  #                               "UKESM_High","UKESM_Low"),
  #                      values=cbPalette12[c(2,4,10,6)],
  #                      name="Climate Model") +
  #   # facet_wrap(~SiteName) +
  #   theme_classic(base_family = "serif", base_size = 16) +
  #   theme(panel.background = element_blank(),
  #         panel.border = element_rect(colour = "darkgrey", fill=NA),
  #         strip.background = element_blank(),
  #         axis.line = element_line(),
  #         legend.position = "right",
  #         legend.key = element_blank())
  # 
  # g_rain2

      ggsave(filename="../../Comb_results_2050/pub_Future_temperature_limited.jpg",
         plot=g_temp_lim, width=8, height=6, dpi=300)
    ggsave(filename="../../Comb_results_2050/pub_Future_precipitation_limited.jpg",
         plot=g_rain_lim, width=9, height=4, dpi=300)
 
```
